apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ecommerce-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - ecommerce
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
    - port: http
      path: /health
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - ecommerce
  selector:
    matchLabels:
      app: user-service
  endpoints:
    - port: http
      path: /health
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - ecommerce
  selector:
    matchLabels:
      app: product-service
  endpoints:
    - port: http
      path: /health
      interval: 30s